### ISSUE TITLE
`make install-oss` is broken due to generating an invalid version

### ISSUE THREAD

**Issue by discentem** [facebook/sapling#733] opened 2023-09-20 21:30 UTC
```
warning: `workingcopy` (lib) generated 1 warning (run `cargo fix --lib -p workingcopy` to apply 1 suggestion)
    Finished release [optimized] target(s) in 1.16s
/opt/homebrew/lib/python3.10/site-packages/setuptools/command/egg_info.py:131: SetuptoolsDeprecationWarning: Invalid version: '4.4.2_20230919-184619-h0972675e'.
!!
        ********************************************************************************
        Version '4.4.2_20230919-184619-h0972675e' is not valid according to PEP 440.
        Please make sure to specify a valid version for your package.
        Also note that future releases of setuptools may halt the build process
        if an invalid version is given.
        By 2023-Sep-26, you need to update your project and remove deprecated calls
        or your builds will no longer be supported.
        See https://peps.python.org/pep-0440/ for details.
        ********************************************************************************
!!
  return _normalization.best_effort_version(tagged)
Traceback (most recent call last):
  File "/Users/brandonk/sapling/eden/scm/setup.py", line 1365, in <module>
    setup(
  File "/opt/homebrew/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/opt/homebrew/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/opt/homebrew/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/opt/homebrew/lib/python3.10/site-packages/setuptools/dist.py", line 1233, in run_command
    super().run_command(command)
  File "/opt/homebrew/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/opt/homebrew/lib/python3.10/site-packages/setuptools/_distutils/command/install.py", line 708, in run
    self.run_command(cmd_name)
  File "/opt/homebrew/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/opt/homebrew/lib/python3.10/site-packages/setuptools/dist.py", line 1233, in run_command
    super().run_command(command)
  File "/opt/homebrew/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.ensure_finalized()
  File "/opt/homebrew/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
    self.finalize_options()
  File "/opt/homebrew/lib/python3.10/site-packages/setuptools/command/install_egg_info.py", line 24, in finalize_options
    ei_cmd = self.get_finalized_command("egg_info")
  File "/opt/homebrew/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 305, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/opt/homebrew/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
    self.finalize_options()
  File "/opt/homebrew/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 225, in finalize_options
    parsed_version = packaging.version.Version(self.egg_version)
  File "/opt/homebrew/lib/python3.10/site-packages/setuptools/_vendor/packaging/version.py", line 198, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
setuptools.extern.packaging.version.InvalidVersion: Invalid version: '4.4.2-20230919-184619-h0972675e'
make: *** [install-oss] Error 1
```

This can be worked around by setting `SAPLING_VERSION=4.4.2`: `SAPLING_VERSION=4.4.2 make install-oss`

**Comment by vegerot** [comment] 2023-10-02 18:15
I think this is a duplicate of #714

**Comment by zzl0** [comment] 2023-11-10 15:25
this is fixed in https://github.com/facebook/sapling/commit/14d92511d6abe143f5d6cfa30020e755dc87c290

**Closed by zzl0** 2023-11-10 15:25 UTC
