### ISSUE TITLE
When update on Manjaro, a ArchLinux based distribution, with `yay `, a error rose.

### ISSUE THREAD

**Issue by gnu4cn** [facebook/sapling#549] opened 2023-03-04 00:15 UTC
```console
packaging.version.InvalidVersion: Invalid version: '4.4.2-20230228-205357-heb50b90a'
make: *** [Makefile:92: install-oss] Error 1
```

This error might caused by SemVer problem.

**Comment by sggutier** [comment] 2023-03-04 00:37
Closing as this seems to be a duplicate of  #548

**Closed by sggutier** 2023-03-04 00:37 UTC
