### ISSUE TITLE
Using on existing local git repo

### ISSUE THREAD

**Issue by noamelf** [facebook/sapling#145] opened 2022-11-15 21:22 UTC
Wanting to check out Sapling, I installed it and tried to run it on a local (already cloned) repo, it didn't work.
It's easier for me to start using it on existing repos instead of re-cloning all the repos with Sapling. So I guess I'm asking if that is supported, or not. I tried looking it up but couldn't find anything about it in the docs.

**Comment by quark-zju** [comment] 2022-11-16 04:47
Unfortunately, a new clone is required. https://sapling-scm.com/docs/internals/internal-difference-hg#git-support explains some motivation behind this.

I'm closing this since this works as designed. Feel free to follow up if you have further questions.

**Closed by quark-zju** 2022-11-16 04:47 UTC

**Comment by noamelf** [comment] 2022-11-16 07:16
Ok, thanks for the response
