### ISSUE TITLE
How to use sapling with GitLab?

### ISSUE THREAD

**Issue by gnu4cn** [facebook/sapling#297] opened 2022-12-02 09:49 UTC
It seems that this scm only works with github, but I hosted a GitLab server, when I run `sl pull` under a cloned GitLab repo, it gave me the message:

```console
$ sl pull                                                                                                                                          lennyp@vm-manjaro
pulling from ssh://git@gitlab.xfoss.com/lenny.peng/c-intro-and-ref.git
abort: Either gitlab.xfoss.com is not a GitHub Enterprise hostname or you are not logged in.
Authenticate using the GitHub CLI: `gh auth login --git-protocol https --hostname gitlab.xfoss.com`
warning: post-pull.prmarker hook exited with status 255
```

So sad about this.

**Comment by zzl0** [comment] 2022-12-03 00:15
@gnu4cn thanks for reporting the issue, this is duplicate of #177, closing this one

**Comment by bolinfest** [comment] 2022-12-03 00:42
I think this is different than #177 as that one was asking about things like pull request integration, where this seems like an attempt to do something more fundamental, just `sl pull`, which should work.

**Comment by bolinfest** [comment] 2022-12-03 01:16
@gnu4cn I assume you did `sl clone ssh://git@gitlab.xfoss.com/lenny.peng/c-intro-and-ref.git` to create the repo in the first place? Also, what does `sl --version` print? There may be a regex or other logic that things this is a GitHub [Enterprise] instance for some reason.

**Comment by gnu4cn** [comment] 2022-12-05 01:32
@bolinfest, Sorry so late for replying you, I am hosting an GitLab CE instance locally. and I installed sapling `sl` from an Manjaro(Archlinux) host, so it should be the latest version. The `sl --version` shows:

```console
$ sl --version                                                                                                                 lennyp@vm-manjaro
Sapling 4.4.2
```

> @gnu4cn I assume you did `sl clone ssh://git@gitlab.xfoss.com/lenny.peng/c-intro-and-ref.git` to create the repo in the first place? Also, what does `sl --version` print? There may be a regex or other logic that things this is a GitHub [Enterprise] instance for some reason.

**Comment by gnu4cn** [comment] 2022-12-05 01:47
@bolinfest 

Here are the detailed outputs:

```console
~ > sl clone git@gitlab.senscomm.com:lenny.peng/c-intro-and-ref.git                                                              lennyp@vm-manjaro
~ > cd c-intro-and-ref                                                                                                           lennyp@vm-manjaro
~/c-intro-and-ref > sl pull                                                                                                      lennyp@vm-manjaro
pulling from ssh://git@gitlab.senscomm.com/lenny.peng/c-intro-and-ref.git
abort: Either gitlab.senscomm.com is not a GitHub Enterprise hostname or you are not logged in.
Authenticate using the GitHub CLI: `gh auth login --git-protocol https --hostname gitlab.senscomm.com`
warning: post-pull.prmarker hook exited with status 255
~/c-intro-and-ref >                   
```

**Comment by gnu4cn** [comment] 2022-12-05 01:48
@bolinfest 

Here are the detailed outputs:

```console
~ > sl clone git@gitlab.xfoss.com:lenny.peng/c-intro-and-ref.git                                                              lennyp@vm-manjaro
~ > cd c-intro-and-ref                                                                                                           lennyp@vm-manjaro
~/c-intro-and-ref > sl pull                                                                                                      lennyp@vm-manjaro
pulling from ssh://git@gitlab.xfoss.com/lenny.peng/c-intro-and-ref.git
abort: Either gitlab.xfoss.com is not a GitHub Enterprise hostname or you are not logged in.
Authenticate using the GitHub CLI: `gh auth login --git-protocol https --hostname gitlab.xfoss.com`
warning: post-pull.prmarker hook exited with status 255
~/c-intro-and-ref >                   
```

**Comment by gnu4cn** [comment] 2022-12-05 05:49
FYI, here is another trying output:

```console
$ sl clone https://gitlab.xfoss.com/lenny.peng/c-intro-and-ref.git                                                          lennyp@vm-manjaro
abort: git command failed with exit code 128
  git '--git-dir=/home/lennyp/c-intro-and-ref/.sl/store/git' ls-remote --refs 'https://gitlab.xfoss.com/lenny.peng/c-intro-and-ref.git' refs/heads/main refs/heads/master
    致命错误：无法访问 'https://gitlab.xfoss.com/lenny.peng/c-intro-and-ref.git/'：SSL certificate problem: unable to get local issuer certificate
```

**Comment by bolinfest** [comment] 2022-12-05 18:42
@gnu4cn Hmm, so I see a couple potential issues here:

1. The output of `sl --version` suggests that your version of Sapling was built from source somehow. I have no idea what command was used, or what commit it was built from. Admittedly, if you are on Arch, building from source is the only option since only provide `.deb` files at the moment: we haven't gotten around to providing `.rpm` or AppImage yet. Nevertheless, because I don't know what the true version of your `sl` is, it's hard for me to know whether this is an issue that is fixed in a newer version or not.
2. Based on the `SSL certificate problem` in the error message, I would ask what mechanism you use, if any, to use regular `git` without having to enter a password/passphrase every time you `git push`. If you're using an https URI, then I *think* you need to set up a Git credential helper of some kind: https://git-scm.com/docs/gitcredentials. If you're using an ssh URI, then perhaps you need to do something in your `~/.ssh/config`. For example, GitHub users can use `gh` as their credential manager for GitHub repositories like this: https://sapling-scm.com/docs/git/intro#troubleshooting

**Comment by zzl0** [comment] 2022-12-05 21:37
The `pull` error looks similar to issue #229, which is fixed in the new version.

**Comment by bolinfest** [comment] 2022-12-07 06:51
Closing, but feel free to reopen if you can confirm this is still a problem using the latest release.

**Closed by bolinfest** 2022-12-07 06:51 UTC

**Comment by gnu4cn** [comment] 2022-12-12 03:17
Thanks a lot for your kindly reply.

**Comment by gnu4cn** [comment] 2022-12-12 05:28
@bolinfest Now, the sapling works with my local hosted GitLab CE instance smoothly. 

Thanks a lot for your/the Sapling team's contributions!
