### ISSUE TITLE
'AttributeError' object has no attribute 'name'

### ISSUE THREAD

**Issue by yonas** [facebook/sapling#825] opened 2024-01-24 21:16 UTC
```
$ sl config --user ui.username "Yonas <yonas@example.lan>"
warning: extension automv is disabled because it cannot be imported: 'AttributeError' object has no attribute 'name'
warning: extension blackbox is disabled because it cannot be imported: 'AttributeError' object has no attribute 'name'
warning: extension conflictinfo is disabled because it cannot be imported: 'AttributeError' object has no attribute 'name'
warning: extension copytrace is disabled because it cannot be imported: 'AttributeError' object has no attribute 'name'
warning: extension dialect is disabled because it cannot be imported: 'AttributeError' object has no attribute 'name'
warning: extension dirsync is disabled because it cannot be imported: 'AttributeError' object has no attribute 'name'
warning: extension extorder is disabled because it cannot be imported: 'AttributeError' object has no attribute 'name'
warning: extension logginghelper is disabled because it cannot be imported: 'AttributeError' object has no attribute 'name'
warning: extension morestatus is disabled because it cannot be imported: 'AttributeError' object has no attribute 'name'
warning: extension myparent is disabled because it cannot be imported: 'AttributeError' object has no attribute 'name'
warning: extension progressfile is disabled because it cannot be imported: 'AttributeError' object has no attribute 'name'
warning: extension traceprof is disabled because it cannot be imported: 'AttributeError' object has no attribute 'name'
warning: extension mergedriver is disabled because it cannot be imported: 'AttributeError' object has no attribute 'name'
warning: extension sampling is disabled because it cannot be imported: 'AttributeError' object has no attribute 'name'
```

OS: `FreeBSD 14.0`
Sapling: `4.4.2_20240124-074559-h1b6e9a62`

**Comment by classner** [comment] 2024-02-03 00:17
This is a bit short as a bug report, but this happens for me for any sl command. Would be great to hear back from the authors what this problem is related to?

**Comment by zzl0** [comment] 2024-02-04 05:36
Thanks for the feedback.

Did you build Sapling from source? What is your Python version? The `AttributeError.name` was introduced in Python 3.10.

**Comment by zzl0** [comment] 2024-02-04 06:06
We have a fix ready!

If you build it from source code, you can apply this patch to unblock yourself.
```
diff --git a/eden/scm/sapling/extensions.py b/eden/scm/sapling/extensions.py
--- a/eden/scm/sapling/extensions.py
+++ b/eden/scm/sapling/extensions.py
@@ -374,6 +374,11 @@
     try:
         return getattr(obj, name)
     except AttributeError as e:
+        # AttributeError.name was added in 3.10, let's
+        # skip the check if Python version is < 3.10
+        if sys.version_info < (3, 10):
+            return default
+
         if e.name == name:
             return default
         else:
```

**Comment by classner** [comment] 2024-02-04 06:21
Hey @zzl0 !

Thanks for the quick turnaround! I did build from source. Weirdly, even after applying the fix, doing a `make clean` and then a `make oss` the behavior remains the same for me. Is there anything else I have to do for this fix to be picked up in the build?

**Comment by zzl0** [comment] 2024-02-04 15:59
@classner rebuild should work. Could you share more information about your environment?

1. What Python version are you using? run `./sl debugpython`
2. Could you share the reproduce commands?

**Comment by classner** [comment] 2024-02-05 10:24
Hmmm, weird. Sure:

1. It's a Python 3.9.16 (GCC 9.4.0) on Linux. Funny enough, that's not my system Python (that's a 3.8.10) and I do not know where it is pulled in from. Does sapling download it's own Python?
2. The warnings show up for any command run, for example even for a simple `./sl --help`.

**Comment by zzl0** [comment] 2024-02-05 15:59
> Does sapling download its own Python?

It tries to pick a Python from your local: https://github.com/facebook/sapling/blob/main/eden/scm/contrib/pick_python.py#L41-L45

> The warnings show up for any command run, for example even for a simple ./sl --help

This wired. Could you reliably reproduce it? for example the exact steps of how you built and tested it:

```
$ git clone https://github.com/facebook/sapling.git
$ cd sapling/eden/scm
$ # apply the patch
$ git diff # show the diff of the change
$ make oss
$ ./sl --help
$ ./sl debugpython
Python 3.8.17 (default, Jul  9 2023, 20:57:35)
[Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.version_info < (3, 10)
True
```

**Comment by zzl0** [comment] 2024-02-05 19:27
I just landed the fix to the latest code

**Comment by zzl0** [comment] 2024-02-06 21:09
feel free to open it if you still see the issue

**Comment by classner** [comment] 2024-02-06 22:37
Hi @zzl0 !

Thanks a lot for the swift turnaround! I am still facing this issue, even on the latest `main`. I built sapling with Python 3.10, _and even then_ this issue is surfacing. I made sure I am running correctly in Python 3.10 by doing an `sl debugpython` and the right Python is being loaded. So something else is triggering this problem. I understand that you have not been able to reproduce this yourself?

**Comment by classner** [comment] 2024-02-06 22:38
(I am not able to reopen the issue myself to make it trackable again.)

**Comment by zzl0** [comment] 2024-02-07 01:17
@classner could you share the commands that you ran and their output on your side? OS platform?

**Comment by classner** [comment] 2024-02-07 17:12
Figured it out: this _was_ an issue on my end, since I had originally installed sapling using the .deb package and even after doing a `dpkg -r` and `apt autoremove` load path pollution or configuration pollution persisted until rebooting the system and the source-compiled version still picked up some ghost packages. Confirming that this issue has been resolved, thanks a lot for the quick turnaround.

**Closed** 2024-02-07 19:53 UTC
Labels: fix ready
