### ISSUE TITLE
could not read paths.default

### ISSUE THREAD

**Issue by fgsch** [facebook/sapling#273] opened 2022-11-26 12:15 UTC
Version:

`Sapling 0.1.20221118-210929-cfbb68aa`

Steps:

```sh
sl init --git  sl-test
cd sl-test
touch a
sl add a
sl commit
```

Running `sl` shows:

`abort: could not read paths.default`

Running `sl sm` however shows the expected results:

```
@  changeset:   02a11753880378e9be95d85eefa30b14b1702e42  (@)
   user:        User <user@domain>
   date:        Sat, 26 Nov 2022 12:11:51 +0000
   summary:     title
```

Is this expected?

**Comment by sggutier** [comment] 2022-11-28 00:03
Thanks for reporting the issue. 

As a temporary workaround, you can change the value of `commands.naked-default.in-repo`, which controls the default command/alias for `sl` to `smartlog` in your config file. `sl` is actually an alias for `smartlog -T '{sl}'`

**Comment by bolinfest** [comment] 2022-12-09 06:04
I can't reproduce this with Sapling 0.1.20221201-095354-r360873f1, so it seems this has been fixed. I'm going to close this issue, but please reopen if you have repro steps with the latest release.

**Closed by bolinfest** 2022-12-09 06:04 UTC
Labels: bug, config
